pushed

diff --git a/release/updated-manifests.yaml b/release/updated-manifests.yaml
--- a/release/updated-manifests.yaml
+++ b/release/updated-manifests.yaml
@@ -33,7 +33,8 @@ spec:
       terminationGracePeriodSeconds: 5
       containers:
       - name: server
-        image: gcr.io/google-samples/microservices-demo/emailservice:v0.3.6
+        image: emailservice
+        #image: gcr.io/google-samples/microservices-demo/emailservice:v0.3.6
         ports:
         - containerPort: 8080
         env:
@@ -88,7 +89,8 @@ spec:
       serviceAccountName: default
       containers:
         - name: server
-          image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.3.6
+          image: checkoutservice
+          #image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.3.6
           ports:
           - containerPort: 5050
           readinessProbe:
@@ -158,7 +160,8 @@ spec:
       terminationGracePeriodSeconds: 5
       containers:
       - name: server
-        image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.3.6
+        #image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.3.6
+        image: recommendationservice
         ports:
         - containerPort: 8080
         readinessProbe:
@@ -219,7 +222,8 @@ spec:
       serviceAccountName: default
       containers:
         - name: server
-          image: gcr.io/google-samples/microservices-demo/frontend:v0.3.6
+          image: frontend
+          #image: gcr.io/google-samples/microservices-demo/frontend:v0.3.6
           ports:
           - containerPort: 8080
           readinessProbe:
@@ -318,7 +322,8 @@ spec:
       terminationGracePeriodSeconds: 5
       containers:
       - name: server
-        image: gcr.io/google-samples/microservices-demo/paymentservice:v0.3.6
+        #image: gcr.io/google-samples/microservices-demo/paymentservice:v0.3.6
+        image: paymentservice
         ports:
         - containerPort: 50051
         env:
@@ -374,7 +379,8 @@ spec:
       terminationGracePeriodSeconds: 5
       containers:
       - name: server
-        image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.3.6
+        #image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.3.6
+        image: productcatalogservice
         ports:
         - containerPort: 3550
         env:
@@ -432,7 +438,8 @@ spec:
       terminationGracePeriodSeconds: 5
       containers:
       - name: server
-        image: gcr.io/google-samples/microservices-demo/cartservice:v0.3.6
+        #image: gcr.io/google-samples/microservices-demo/cartservice:v0.3.6
+        image: cartservice
         ports:
         - containerPort: 7070
         env:
@@ -468,57 +475,57 @@ spec:
     port: 7070
     targetPort: 7070
 ---
-apiVersion: apps/v1
-kind: Deployment
-metadata:
-  name: loadgenerator
-spec:
-  selector:
-    matchLabels:
-      app: loadgenerator
-  replicas: 1
-  template:
-    metadata:
-      labels:
-        app: loadgenerator
-      annotations:
-        sidecar.istio.io/rewriteAppHTTPProbers: "true"
-    spec:
-      serviceAccountName: default
-      terminationGracePeriodSeconds: 5
-      restartPolicy: Always
-      initContainers:
-      - command:
-        - /bin/sh
-        - -exc
-        - |
-          echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
-          STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
-          if test $STATUSCODE -ne 200; then
-              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
-              exit 1
-          fi
-        name: frontend-check
-        image: busybox:latest
-        env:
-        - name: FRONTEND_ADDR
-          value: "frontend:80"
-      containers:
-      - name: main
-        image: gcr.io/google-samples/microservices-demo/loadgenerator:v0.3.6
-        env:
-        - name: FRONTEND_ADDR
-          value: "frontend:80"
-        - name: USERS
-          value: "10"
-        resources:
-          requests:
-            cpu: 300m
-            memory: 256Mi
-          limits:
-            cpu: 500m
-            memory: 512Mi
----
+# apiVersion: apps/v1
+# kind: Deployment
+# metadata:
+#   name: loadgenerator
+# spec:
+#   selector:
+#     matchLabels:
+#       app: loadgenerator
+#   replicas: 1
+#   template:
+#     metadata:
+#       labels:
+#         app: loadgenerator
+#       annotations:
+#         sidecar.istio.io/rewriteAppHTTPProbers: "true"
+#     spec:
+#       serviceAccountName: default
+#       terminationGracePeriodSeconds: 5
+#       restartPolicy: Always
+#       initContainers:
+#       - command:
+#         - /bin/sh
+#         - -exc
+#         - |
+#           echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
+#           STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
+#           if test $STATUSCODE -ne 200; then
+#               echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
+#               exit 1
+#           fi
+#         name: frontend-check
+#         image: busybox:latest
+#         env:
+#         - name: FRONTEND_ADDR
+#           value: "frontend:80"
+#       containers:
+#       - name: main
+#         image: gcr.io/google-samples/microservices-demo/loadgenerator:v0.3.6
+#         env:
+#         - name: FRONTEND_ADDR
+#           value: "frontend:80"
+#         - name: USERS
+#           value: "10"
+#         resources:
+#           requests:
+#             cpu: 300m
+#             memory: 256Mi
+#           limits:
+#             cpu: 500m
+#             memory: 512Mi
+# ---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
@@ -536,7 +543,8 @@ spec:
       terminationGracePeriodSeconds: 5
       containers:
       - name: server
-        image: gcr.io/google-samples/microservices-demo/currencyservice:v0.3.6
+        #image: gcr.io/google-samples/microservices-demo/currencyservice:v0.3.6
+        image: currencyservice
         ports:
         - name: grpc
           containerPort: 7000
@@ -592,7 +600,8 @@ spec:
       serviceAccountName: default
       containers:
       - name: server
-        image: gcr.io/google-samples/microservices-demo/shippingservice:v0.3.6
+        #image: gcr.io/google-samples/microservices-demo/shippingservice:v0.3.6
+        image: shippingservice
         ports:
         - containerPort: 50051
         env:
@@ -634,59 +643,59 @@ spec:
     port: 50051
     targetPort: 50051
 ---
-apiVersion: apps/v1
-kind: Deployment
-metadata:
-  name: redis-cart
-spec:
-  selector:
-    matchLabels:
-      app: redis-cart
-  template:
-    metadata:
-      labels:
-        app: redis-cart
-    spec:
-      containers:
-      - name: redis
-        image: redis:alpine
-        ports:
-        - containerPort: 6379
-        readinessProbe:
-          periodSeconds: 5
-          tcpSocket:
-            port: 6379
-        livenessProbe:
-          periodSeconds: 5
-          tcpSocket:
-            port: 6379
-        volumeMounts:
-        - mountPath: /data
-          name: redis-data
-        resources:
-          limits:
-            memory: 256Mi
-            cpu: 125m
-          requests:
-            cpu: 70m
-            memory: 200Mi
-      volumes:
-      - name: redis-data
-        emptyDir: {}
----
-apiVersion: v1
-kind: Service
-metadata:
-  name: redis-cart
-spec:
-  type: ClusterIP
-  selector:
-    app: redis-cart
-  ports:
-  - name: redis
-    port: 6379
-    targetPort: 6379
----
+# apiVersion: apps/v1
+# kind: Deployment
+# metadata:
+#   name: redis-cart
+# spec:
+#   selector:
+#     matchLabels:
+#       app: redis-cart
+#   template:
+#     metadata:
+#       labels:
+#         app: redis-cart
+#     spec:
+#       containers:
+#       - name: redis
+#         image: redis:alpine
+#         ports:
+#         - containerPort: 6379
+#         readinessProbe:
+#           periodSeconds: 5
+#           tcpSocket:
+#             port: 6379
+#         livenessProbe:
+#           periodSeconds: 5
+#           tcpSocket:
+#             port: 6379
+#         volumeMounts:
+#         - mountPath: /data
+#           name: redis-data
+#         resources:
+#           limits:
+#             memory: 256Mi
+#             cpu: 125m
+#           requests:
+#             cpu: 70m
+#             memory: 200Mi
+#       volumes:
+#       - name: redis-data
+#         emptyDir: {}
+# ---
+# apiVersion: v1
+# kind: Service
+# metadata:
+#   name: redis-cart
+# spec:
+#   type: ClusterIP
+#   selector:
+#     app: redis-cart
+#   ports:
+#   - name: redis
+#     port: 6379
+#     targetPort: 6379
+# ---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
@@ -704,7 +713,8 @@ spec:
       terminationGracePeriodSeconds: 5
       containers:
       - name: server
-        image: gcr.io/google-samples/microservices-demo/adservice:v0.3.6
+        #image: gcr.io/google-samples/microservices-demo/adservice:v0.3.6
+        image: adservice
         ports:
         - containerPort: 9555
         env:
